import mongoose from "mongoose";

const StudentSchema = mongoose.Schema({
  parent_id: { type: String, default: "Not Provided" },
  admission_no: { type: String, default: "Not Provided" },
  admission_date: { type: String, default: "Not Provided" },
  firstname: { type: String, required: true, default: "Not Provided" },
  middlename: { type: String, default: "Not Provided" },
  lastname: { type: String, default: "Not Provided" },
  image: { type: String, default: "Not Provided" },
  mobileno: { type: String, default: "Not Provided" },
  email: { type: String, default: "Not Provided" },
  region: { type: String, default: "Not Provided" },
  city: { type: String, default: "Not Provided" },
  town: { type: String, default: "Not Provided" },
  religion: { type: String, default: "Not Provided" },
  cast: { type: String, default: "Not Provided" },
  dob: { type: String, default: "Not Provided" },
  gender: { type: String, default: "Not Provided" },
  current_address: { type: String, default: "Not Provided" },
  permanent_address: { type: String, default: "Not Provided" },
  class: { type: String, default: "Not Provided" },
  section: { type: String, default: "Not Provided" },
  school_club: { type: String, default: "Not Provided" },
  blood_group: { type: String, default: "Not Provided" },
  medical_condition: { type: String, default: "Not Provided" },
  guardian_is: { type: String, default: "Not Provided" },
  email: { type: String, default: "Not Provided" },
  region: { type: String, default: "Not Provided" },
  city: { type: String, default: "Not Provided" },
  town: { type: String, default: "Not Provided" },
  religion: { type: String, default: "Not Provided" },
  cast: { type: String, default: "Not Provided" },
  dob: { type: String, default: "Not Provided" },
  gender: { type: String, default: "Not Provided" },
  father_name: { type: String, default: "Not Provided" },
  father_phone: { type: String, default: "Not Provided" },
  father_occupation: { type: String, default: "Not Provided" },
  mother_name: { type: String, default: "Not Provided" },
  mother_phone: { type: String, default: "Not Provided" },
  mother_occupation: { type: String, default: "Not Provided" },
  guardian_name: { type: String, default: "Not Provided" },
  guardian_relation: { type: String, default: "Not Provided" },
  guardian_phone: { type: String, default: "Not Provided" },
  guardian_occupation: { type: String, default: "Not Provided" },
  guardian_address: { type: String, default: "Not Provided" },
  guardian_email: { type: String, default: "Not Provided" },
  father_pic: { type: String, default: "Not Provided" },
  mother_pic: { type: String, default: "Not Provided" },
  guardian_pic: { type: String, default: "Not Provided" },
  previous_school: { type: String, default: "Not Provided" },
  height: { type: String, default: "Not Provided" },
  weight: { type: String, default: "Not Provided" },
  measurement_date: { type: String, default: "Not Provided" },
  note: { type: String, default: "Not Provided" },
  created_b: { type: String, default: "Not Provided" },
});
export const Student = mongoose.model("Student", StudentSchema);
